version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "VA-Iknelia"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hqbzflpjeg1y"
s3_prefix = "VA-Iknelia"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
